# Generated by Django 3.2.20 on 2024-04-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driverdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userip', models.CharField(default='', max_length=20)),
                ('isactive', models.BooleanField(default=False)),
            ],
        ),
    ]
