# Generated by Django 3.2.20 on 2024-04-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('led1', models.BooleanField(default=False)),
                ('led2', models.BooleanField(default=False)),
                ('led3', models.BooleanField(default=False)),
                ('led4', models.BooleanField(default=False)),
                ('led5', models.BooleanField(default=False)),
                ('led6', models.BooleanField(default=False)),
                ('led7', models.BooleanField(default=False)),
                ('led8', models.BooleanField(default=False)),
                ('led9', models.BooleanField(default=False)),
                ('led10', models.BooleanField(default=False)),
                ('led11', models.BooleanField(default=False)),
                ('led12', models.BooleanField(default=False)),
                ('led13', models.BooleanField(default=False)),
                ('led14', models.BooleanField(default=False)),
                ('led15', models.BooleanField(default=False)),
                ('led16', models.BooleanField(default=False)),
                ('led17', models.BooleanField(default=False)),
                ('led18', models.BooleanField(default=False)),
                ('led19', models.BooleanField(default=False)),
                ('led20', models.BooleanField(default=False)),
                ('led21', models.BooleanField(default=False)),
                ('led22', models.BooleanField(default=False)),
                ('led23', models.BooleanField(default=False)),
                ('led24', models.BooleanField(default=False)),
                ('led25', models.BooleanField(default=False)),
                ('led26', models.BooleanField(default=False)),
                ('led27', models.BooleanField(default=False)),
                ('led28', models.BooleanField(default=False)),
                ('led29', models.BooleanField(default=False)),
                ('led30', models.BooleanField(default=False)),
                ('led31', models.BooleanField(default=False)),
                ('led32', models.BooleanField(default=False)),
            ],
        ),
    ]
