# Generated by Django 3.2.20 on 2024-04-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leds',
            name='ipaddress',
            field=models.CharField(default='0.0.0.0', max_length=20),
        ),
    ]
