# Generated by Django 3.2.20 on 2024-04-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_leds_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locationrecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=40)),
                ('Lattitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
    ]
