# Generated by Django 3.2.20 on 2024-04-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_locationrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationrecording',
            name='Goingto',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
    ]
