# Generated by Django 3.2.20 on 2024-04-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_auto_20240426_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataforlist',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
