# Generated by Django 3.2.20 on 2024-04-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_alter_dataforlist_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='leds',
            name='led33',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led34',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led35',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led36',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led37',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led38',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led39',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led40',
            field=models.BooleanField(default=False),
        ),
    ]
