# Generated by Django 3.2.20 on 2024-05-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_auto_20240429_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SignalId', models.CharField(max_length=20)),
                ('Lattitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
    ]
