# Generated by Django 3.2.20 on 2024-05-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='leds',
            name='led41',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led42',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led43',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led44',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led45',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led46',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led47',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leds',
            name='led48',
            field=models.BooleanField(default=False),
        ),
    ]
