from django.db import models

class Leds(models.Model):
    ipaddress = models.CharField(max_length=20,default="0.0.0.0")
    led1 = models.BooleanField(default=False)
    led2 = models.BooleanField(default=False)
    led3 = models.BooleanField(default=False)
    led4 = models.BooleanField(default=False)
    led5 = models.BooleanField(default=False)
    led6 = models.BooleanField(default=False)
    led7 = models.BooleanField(default=False)
    led8 = models.BooleanField(default=False)
    led9 = models.BooleanField(default=False)
    led10 = models.BooleanField(default=False)
    led11 = models.BooleanField(default=False)
    led12= models.BooleanField(default=False)
    led13 = models.BooleanField(default=False)
    led14 = models.BooleanField(default=False)
    led15 = models.BooleanField(default=False)
    led16 = models.BooleanField(default=False)
    led17 = models.BooleanField(default=False)
    led18 = models.BooleanField(default=False)
    led19 = models.BooleanField(default=False)
    led20= models.BooleanField(default=False)
    led21 = models.BooleanField(default=False)
    led22 = models.BooleanField(default=False)
    led23= models.BooleanField(default=False)
    led24= models.BooleanField(default=False)
    led25= models.BooleanField(default=False)
    led26= models.BooleanField(default=False)
    led27= models.BooleanField(default=False)
    led28= models.BooleanField(default=False)
    led29= models.BooleanField(default=False)
    led30= models.BooleanField(default=False)
    led31= models.BooleanField(default=False)
    led32= models.BooleanField(default=False)
    led33= models.BooleanField(default=False)
    led34= models.BooleanField(default=False)
    led35= models.BooleanField(default=False)
    led36= models.BooleanField(default=False)
    led37= models.BooleanField(default=False)
    led38= models.BooleanField(default=False)
    led39= models.BooleanField(default=False)
    led40= models.BooleanField(default=False)
    led41= models.BooleanField(default=False)
    led42= models.BooleanField(default=False)
    led43= models.BooleanField(default=False)
    led44= models.BooleanField(default=False)
    led45= models.BooleanField(default=False)
    led46= models.BooleanField(default=False)
    led47= models.BooleanField(default=False)
    led48= models.BooleanField(default=False)
class Locationrecording(models.Model):
    Username = models.CharField(max_length=40)
    Goingto = models.CharField(max_length=20)
    Lattitude = models.FloatField()
    Longitude = models.FloatField()
class Dataforlist(models.Model):
    Username = models.CharField(max_length=100)
    Ambulanceid = models.CharField(max_length=100)
    Hospital = models.CharField(max_length=100)
    Completed = models.BooleanField(default=False)
    Lattitude = models.FloatField()
    Longitude = models.FloatField()
    HospLattitude = models.FloatField()
    HospLongitude = models.FloatField()
    distance = models.CharField(max_length=15,default="0.0")
    def __str__(self):
        return self.Username
class Signals(models.Model):
    SignalId = models.CharField(max_length=20)
    Lattitude = models.FloatField()
    Longitude = models.FloatField()

    def __str__(self):
        return self.SignalId