# Generated by Django 3.2.20 on 2024-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospitalid', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('HospitalName', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=60)),
                ('Lattitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
    ]
