# Generated by Django 3.2.20 on 2024-04-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_alter_hospitals_hospitalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='Password',
        ),
    ]
