# Generated by Django 3.2.20 on 2024-04-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_remove_hospitals_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='Lattitude',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='Longitude',
            field=models.CharField(max_length=15),
        ),
    ]
