# Generated by Django 3.2.20 on 2024-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_auto_20240423_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='logo',
            field=models.CharField(default='https://media.istockphoto.com/id/1303278663/photo/modern-building-facade-with-hospital-word-signage.webp?b=1&s=170667a&w=0&k=20&c=aKpsgxd8GIfH_P--jhp5OZ6UnCDFmfpFdIzuhF5YVtA=', max_length=40),
            preserve_default=False,
        ),
    ]
